### ISSUE TITLE
selectCallback Removed?

### ISSUE THREAD

**Issue by yangkennyk** [Shopify/slate#116]
I'm following this tutorial to add color swatches but it looks like the selectCallback function was removed?

https://help.shopify.com/themes/customization/showcase-products/add-color-swatches

Is there an updated tutorial on how to add swatches?

**Comment by NathanPJF** [comment]
@yangkennyk Slate isn't using the globally hosted `option_selection.js` script which that tutorial requires in order to work.  It's not made clear in that tutorial, but you'd pass `selectCallback` to a property of a new `Shopify.OptionSelectors` instance.  You can find a bit more information about that file here: https://help.shopify.com/themes/customization/products/use-products-with-multiple-options

You can achieve a fair amount of this tutorial with HTML and the [`product.options_with_values` drop](https://help.shopify.com/themes/liquid/objects/product_option) to get the swatches without JavaScript.  For the JS interactions, you'll need to write your own function for your theme in a file like`product.js` ([Slate example](https://github.com/Shopify/slate/blob/master/src/scripts/sections/product.js)) - could be any file you'd want, though.

> Is there an updated tutorial on how to add swatches?

There are no plans to update the existing public tutorials with examples of using Slate at this point.  Writing functionality like swatches is something that would be written into your theme's `/src` files as opposed to in the product templates.

**Comment by yangkennyk** [comment]
thanks for the response! I ended up getting it to work after trial and error.

for the select callback portion I added it to the _onSelectChange method in variants.js

`		/**
		 * Event handler for when a variant input changes.
		 */
		_onSelectChange: function() {
			var variant = this._getVariantFromOptions();
			this.$container.trigger({
				type: 'variantChange',
				variant: variant
			});

			if (!variant) {
				return;
			}

			this._updateMasterSelect(variant);
			this._updateImages(variant);
			this._updatePrice(variant);
			this.currentVariant = variant;

			if (this.enableHistoryState) {
				this._updateHistoryState(variant);
			}
			// BEGIN SWATCHES
			var selector = this.originalSelectorId;
			if (variant) {
				var form = $(selector).closest('form');
				for (var i=0,length=variant.options.length; i<length; i++) {
					var radioButton = form.find('.swatch[data-option-index="' + i + '"] :radio[value="' + variant.options[i] +'"]');
					if (radioButton.size()) {
						radioButton.get(0).checked = true;
					}
				}
			}
			// END SWATCHES
		},`

**Comment by NathanPJF** [comment]
Nice! Glad to hear it's working. 👍 

Going to close this issue now.

**Comment by cobblehillmachine** [comment]
Hey @yangkennyk! Nice job on getting this working in the new framework. Would you mind sharing the modifications you made to get it working? I'm having trouble figuring out how to attach the swatches to the _onSelectChange event.  I'm assuming (perhaps naively) that getting that hooked up will then take care of updating the price, image, and Add to Cart buttons.

**Comment by sebastijandumancic** [comment]
@yangkennyk Same as @cobblehillmachine I'm having trouble making this work. Did you follow all other steps from the Shopify's tutorial at [this link](https://help.shopify.com/themes/customization/showcase-products/add-color-swatches) or did you change anything else? 

I get radio buttons to show, but no value is updated by selecting one radio button. Thanks!

**Comment by yangkennyk** [comment]
@cobblehillmachine @sebastijandumancic 

I can't remember the modifications I made. I just remember it was a lot of trial and error. I'm also using it in combination with the AJAX cart from https://shopify.github.io/Timber/ as well.

you can check out the source code and when I have time I can isolate out what I did. (swamped at the moment!)

https://boxedwaterisbetter.com/products/500ml-boxed-water

**Comment by sebastijandumancic** [comment]
Thanks, I'll look into this 👍

**Comment by Lmiller84** [comment]
@yangkennyk I am trying to get this working as well with no luck. 
I've followed https://help.shopify.com/themes/customization/showcase-products/add-color-swatches 

added the following to variants.js

```
// BEGIN SWATCHES
			var selector = this.originalSelectorId;
			if (variant) {
				var form = $(selector).closest('form');
				for (var i=0,length=variant.options.length; i<length; i++) {
					var radioButton = form.find('.swatch[data-option-index="' + i + '"] :radio[value="' + variant.options[i] +'"]');
					if (radioButton.size()) {
						radioButton.get(0).checked = true;
					}
				}
			}
			// END SWATCHES
``` 

added the following to theme.liquid

```
jQuery(function() {
  jQuery('.swatch :radio').change(function() {
    var optionIndex = jQuery(this).closest('.swatch').attr('data-option-index');
    var optionValue = jQuery(this).val();
    jQuery(this)
      .closest('form')
      .find('.single-option-selector')
      .eq(optionIndex)
      .val(optionValue)
      .trigger('change');
  });
});
```
and this is the form I have in product.liquid

```
<form action="/cart/add" method="post" enctype="multipart/form-data">
      {% unless product.has_only_default_variant %}

        {% for option in product.options %}
          {% include 'swatch' with option %}
        {% endfor %}
          
      {% endunless %}

      <select name="id" class="no-js" data-product-select>
        {% for variant in product.variants %}
          <option
            {% if variant == current_variant %} selected="selected"{% endif %}
            {% unless variant.available %} disabled="disabled"{% endunless %}
            value="{{ variant.id }}">
              {{ variant.title }}
          </option>
        {% endfor %}
      </select>
      <div class="mfp-quantity">
      <label for="Quantity">{{ 'products.product.quantity' | t }}</label>
      <input type="number" id="Quantity" name="quantity" value="1" min="1">

      <button
        type="submit"
        name="add"
        data-add-to-cart
        {% unless current_variant.available %}disabled="disabled"{% endunless %}>
          <span data-add-to-cart-text>
            {% if current_variant.available %}
              {{ 'products.product.add_to_cart' | t }}
            {% else %}
              {{ 'products.product.sold_out' | t }}
            {% endif %}
          </span>
      </button>
    </form>
```

Any idea what Im missing?

**Comment by sebtchoup** [comment]
@sebastijandumancic @yangkennyk @cobblehillmachine Did you all figure this out? I'm trying to determine if adding the Timber Ajax cart is necessary to get the radio buttons jiving with variant.js.  Working on isolating the timber ajax cart files at the moment, would appreciate the help, and I'm happy to make a Slate fork with Timber Ajax Cart, or otherwise document the drop down to radio button conversion since this I've seen lots of questions but no solutions as of yet.

**Comment by dirad** [comment]
I was able to make this work by fusing the existing slate loop for , and the one from the product-options

look like so:


>     <form action="/cart/add" method="post" enctype="multipart/form-data">
>       {% unless product.has_only_default_variant %}
>         {% for option in product.options_with_values %}
>           <div class="selector-wrapper js swatch">
>             {%- assign i = forloop.index0 -%}
>             <h1>
>               {{ option.name }}
>             </h1>
>             <span><a href="#{{ option.name }}-info" class="link-more-info" title="info about {{ option.name }}">(i)</a></span>
>             {% for value in option.values %}            
>               <input class="swatch-element" id="SingleOptionSelector-{{ i }}-{{ value | handle }}" data-single-option-selector data-index="option{{ option.position }}" type="radio" name="SingleOptionSelector-{{ i }}" value="{{ value | escape }}"{% if forloop.first %} checked{% endif %}  {% unless current_variant.available %}disabled="disabled"{% endunless %} >
>               <label for="SingleOptionSelector-{{ i }}-{{ value | handle }}"><span>{{ value }}</span></label>
>             {% endfor %}
>           </div>
>         {% endfor %}
>       {% endunless %}
> 
>       <select name="id" class="no-js" data-product-select>
>         {% for variant in product.variants %}
>           <option
>             {% if variant == current_variant %}selected="selected"{% endif %}
>             {% unless variant.available %}disabled="disabled"{% endunless %}
>             value="{{ variant.id }}">
>               {{ variant.title }}
>           </option>
>         {% endfor %}
>       </select>
> 
>       <div data-price-wrapper>
>         <span data-product-price>
>           {{ current_variant.price | money }}
>         </span>
> 
>         {% if product.compare_at_price_max > product.price %}
>           <span class="visually-hidden" data-compare-text>{{ 'products.product.regular_price' | t }}</span>
>           <s data-compare-price>
>             {% if current_variant.compare_at_price > current_variant.price %}
>               {{ current_variant.compare_at_price | money }}
>             {% endif %}
>           </s>
>         {% endif %}
>       </div>
> 
>       <button
>         type="submit"
>         name="add"
>         data-add-to-cart
>         {% unless current_variant.available %}disabled="disabled"{% endunless %}>
>           <span data-add-to-cart-text>
>             {% if current_variant.available %}
>               {{ 'products.product.add_to_cart' | t }}
>             {% else %}
>               {{ 'products.product.sold_out' | t }}
>             {% endif %}
>           </span>
>       </button>
>     </form>
> 


AND 
adding the swatches code to _onSelectChange function in variant.js [like @yangkennyk]

👍

**Comment by joshbedo** [comment]
@dirad just tried the following but the variants don't seem to be changing the state correctly. Any ideas? Kind of hitting my head against the wall with this one.

**Comment by joshbedo** [comment]
Note: it doesn't even look like my `_onSelectChange` is firing for variant. I put a debugger there in the function is never called.

**Comment by joshbedo** [comment]
Figured it out my product.liquid file wasnt including this in the container div so events weren't being attached. Seems to be working now.
```
    {% unless product == empty %}
      <script type="application/json" data-product-json>
        {{ product | json }}
      </script>
    {% endunless %}
```

**Comment by dirad** [comment]
@joshbedo 
> my product.liquid file wasnt including this

did you remove it? i am guessing we are both using Slate and should have similar `product.liquid` files...

**Comment by curiouscrusher** [comment]
Has anybody gotten this working with variant history functioning as well?

Using the snippet @dirad posted along with the change to the `variants.js` from @yangkennyk has the swatches mostly working for me. However 2 issues still remain:

1. Having the first variant out of stock doesn't show on page load. I believe this is because the `if (variant.available)` isn't running until `_onSelectChange` is triggered. Still digging on this though. If you select another variant, then select the first again the out of stock will show though.
2. Second issue I'm seeing is with the variant history. Despite it being enabled in the product form `data-enable-history-state="true"` it's not working correctly, whenever you refresh the page after selecting a variant, it defaults the swatches back to the first variant (even if it's out of stock) regardless of the variant parameter that's set in the page url. I'm thinking it has something to do with the dom structure of the swatches, because the history works fine with the stock slate or debut variant dropdowns.

I'm still debugging this, but if anybody has suggestions they would be most welcome. If this feature is fully functional on slate that would be awesome! It still amazes me that swatches and sub-categories are not native to Shopify..

**Comment by dirad** [comment]
@curiouscrusher 
In my case the swatches do update according to the URI [even without the change trigger] , and if i add the loaded variant to the cart, it shows up correctly. 

However the checked options are not displaying correctly.  They always show the first option as checked. 
Furthermore, if i look at the DOM and change an option, the checked value doesnt change from one input to the other but the CSS i wrote for it shows as if it did!

**Comment by curiouscrusher** [comment]
@dirad You're correct, without customization it'll always grab the first available product.

**Comment by beckbailey** [comment]
@dirad I've been going mad trying to figure this out.  Thank you so much for your helpful post!

**Comment by adriangzz** [comment]
I made a quick view on the collection pages. The _onSelectChange is not firing. I got this working on the individual product pages but cant make it work on the collection page. Does anybody knows how?

**Comment by adrianocr** [comment]
I got the swatches to work correctly except for when the page is reloaded. If you refresh the page is just selects the first swatch. Any way to go around this?

**Comment by amwallace** [comment]
@dirad Thanks so much for your help with this.

Has anyone figured out how to get the swatches to select the radio button after a refresh? @adrianocr example isn't working for me.

**Comment by amwallace** [comment]
@dirad Thanks so much for your help with this.

I've figured out how to get the refresh to work using @dirad's fix.

Just replace this line within the input:
{% if forloop.first %} checked{% endif %}

With the follow:
`{% if option.selected_value == value %} checked{% endif %}`
