### ISSUE TITLE
Cart Item Quantity Translation Missing

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate#138]
### Problem

When using the Slate Cart template, there is a Shopify error message caused by a missing translation.

Using `{{ 'cart.general.item_quantity' | t }}` found within the Quantity Input element produces this error message:

> translation missing: en.cart.general.item_quantity

![slate translation missing](https://cloud.githubusercontent.com/assets/18140157/25594973/e7793dc6-2eba-11e7-8a01-2a21c4c2f179.png)

### Scope

Theme Scaffolding

### Replication steps

Load the default Slate cart template in your browser with at least one item in your cart, and using Inspector tools, view the Quantity element for an item, you'll see the `aria-label` contains this issue.

**Comment by ConduciveMammal** [comment]
I've just noticed there's also a missing translation for `{{ 'cart.general.continue_browsing_html' | t }}`

**Comment by chrisberthe** [comment]
Hi @ConduciveMammal, I'm not seeing that on my side. I `slate theme theme-name`'d, pushed to my store, and I see this:

<img src="https://cloud.githubusercontent.com/assets/991693/25632738/ce3dce20-2f42-11e7-9652-bac9c7fda470.png" width="500">

I also notice the translations are there for both `{{ 'cart.general.item_quantity' | t}}` and `{{ 'cart.general.continue_browsing_html' | t }}`. I also started to implement a new `slate test` command to test for mismatched translations [here](https://github.com/Shopify/slate-tools/pull/55). I ran `slate test` on the directory and get back that there were no errors:

<img src="https://cloud.githubusercontent.com/assets/991693/25632857/366f8330-2f43-11e7-961b-ad5aa5a64729.png" width="400">

**Comment by ConduciveMammal** [comment]
Hey @chrisberthe, 
Hmm, that's strange. Perhaps the initial slate config was somehow corrupted?

I actually just checked my `en.default.json` language file and both missing translations are actually there, just not being read for some reason.

![slate translation example](https://cloud.githubusercontent.com/assets/18140157/25639071/7bd50028-2f82-11e7-9fb8-c80a29ef8f3b.png)

I just tried using `slate test` but it returned `Unknown command: test`.

`slate -v` states that I'm rocking Slate 0.9.1. 
NPM states this is the latest version but can't be certain.

Either on the Slate docs or here on GitHub, could a changelog with version numbers and release dates be added?

Also, when starting ThemeKit, if there's an update, the CMD will show this, could something like that be added to Slate?

![themekit-update](https://cloud.githubusercontent.com/assets/18140157/25638908/e387294a-2f81-11e7-8fcf-6a5a54bc304b.png)

**Comment by chrisberthe** [comment]
I'm wondering if the file could have been corrupted as well - but I haven't seen or heard of that issue before.

The `slate test` command, at the time of writing my last comment, wasn't yet released. The PR was merged last week though so you should be able to create a new theme and try the command to see the output.

As for the Theme Kit style notification, we do have something similar implemented for Slate CLI already (using this [NPM package](https://www.npmjs.com/package/update-notifier)) - it's only fired once a week, and we haven't released a newer version for Slate CLI in a bit which is why you might not have seen it yet.

The scope of this issue is kind of derailing. Would you mind closing this issue if the original missing translation issue has been resolved?
