### ISSUE TITLE
Sections and .scss

### ISSUE THREAD

**Issue by sarcos** [Shopify/slate#142]
Hi,
is it possible to access section settings from .scss files ? Basicaly, I want to be able to set css value from the Section editor and use them in the corresponding scss 'modules'.
If I rename site-header.scss to site-header.scss.liquid it can access settings.bg_color but not section.settings.bg_color. hope that make sense !

**Comment by sarcos** [comment]
it seems that won't work. Editor CSS is directly on header.liquid for that reason in the default template.

**Comment by ConduciveMammal** [comment]
@sarcos Liquid isn't available inside the `{% stylesheet 'scss' %}` as Shopify's compiler takes all of the SCSS from each section and compiles it into one single `styles_compiled.css` file.

I'm afraid you'll need to use an external `*.css.liquid` file to be able to use Liquid.

**Comment by t-kelly** [comment]
@sarcos The way that we've been managing section styles controlled by section settings is inline css `<style>` blocks in our Liquid with a selector unique to that section, e.g. 
```
<div id="{{ section.id }}">
  <!-- Section content -->
</div>

<style>
  #{{ section.id }} {
    background-color: {{ section.settings.background_color }};
  }
</style>
```

This allows multiple sections of the type to adhere to their own settings. The same principle can be applied to blocks.

Haven't figured out how best to integrate settings into `.scss` 😞

**Comment by sarcos** [comment]
@t-kelly thank you for clarifying. that make sense, sections are unique and kind of encapsulated by design ! that is not a big deal, but when I saw how you created `styles/modules` folder I thought I could put the section styles (controlled by the editor) in there. I guess it all depends on how the final `CSS` is built.

**Comment by NathanPJF** [comment]
Just a bit more context on section settings and scope:

As explained to me by devs that built the new editor, having the CSS/SCSS of a section scoped to only that section is one of the things that allows the Editor to be fast.  If section settings were accessible in other CSS `*.liquid` files like `theme.scss.liquid`, then changing a value in the section settings would trigger a rebuild of that entire `theme.scss.liquid` file.

But it's not just CSS scope that the devs had to think about.  If sections setting values, like select dropdowns or text, were accessible outside of that section: page renderings would be a lot heavier.  For example: if the value of a `textarea` from a `testimonials.liquid` section was accessible in other sections, then the Editor would have been built to go rerender the *entire* page instead of rerendering just the affected section.  (Entire page because it's more efficient that going through _every_ section and template to verify whether the Liquid needed to be recompiled)

Ultimately: when the editor was built, it was prioritized for the experience the merchant gets.  Having the editor be as fast as we can make it allows us to meet the expectation of instant feedback.

**Comment by andrewjireland** [comment]
Hey guys, given section settings aren't accessible in other .scss files, I'm a little bit unsure of what best practice is for dealing with javascript/scss with sections in themes to be submitted to the theme store.

According to the theme store requirements page; 

> All JavaScript and CSS for sections is stored in theme assets (javascript and stylesheet Liquid tags are not used)

...which seems to contradict a lot of what's directed in Shopify articles on sections, and generally isn't a workable solution if section specific settings are needed.

As @t-kelly mentioned, In Shopify's own narrative theme, sections have <style> tags contained within, which seems to go against this requirement. I've been storing section styles in section specific .scss files (keeping everything modular), and where section specific settings are required, using inline styles, or style tags within the section  — can anyone confirm what what developers should 'officially' be doing to develop an acceptable theme?

**Comment by ConduciveMammal** [comment]
I tend to use data-attributes for Section-related JavaScript.

`<div class="slider" data-slider data-arrows="{{ section.settings.enable_arrows}}"></div>`
Which renders to
`<div class="slider" data-slider data-arrows="true"></div>`

And then in the JS, you can do something like
```js
$('[data-slider]').slick({
  dots: $('data-slider]').data('arrows')
)};
```

**Comment by andrewjireland** [comment]
Thanks @ConduciveMammal, I've been doing the same thing for section-specific javascript — good to know I'm not alone in that! 

The thing I've struggled to wrap my head around (in terms of being accepted re: theme store guidelines)  is section-specific settings where they relate to CSS styles. I.e. overriding the background-color of an element for section/blocks in the theme editor Any ideas there? I've been using <style> tags wrapped in conditional liquid, or when overriding a base style, using inline styles referencing the 'section.settings' liquid reference. These methods work, however, I'd like to make sure Shopify will accept it!

**Comment by jonathanmoore** [comment]
@andrewjireland What you're describing is the accepted approach for free and premium themes. The theme's primary CSS/SCSS file defines the default styling, and the section's custom styling variations are overwritten in the `<style>` tags inside the section.

If your curious about the exact approach, I would recommend downloading Debut or another free Shopify theme to inspect how the Shopify team approaches it.
