### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by lukekhamilton** [Shopify/slate#181]
I've recently started to look at this project for future shopify theme development. So far to me it looks like a very manual process of importing JS/CSS/SCSS libraries into a theme. I was wondering if webpack could be looked at for better managing this process locally? This could also them help get around the issues that currently exist with the shopify servers not supporting the later versions of SCSS too. 

This would then enable much easier management of npm modules so a dev can import and keep a theme updated without a lot of manual overhead. 

Love to know if this has been considered at all?

**Comment by infernalsirius** [comment]
Hi @lukekhamilton, if I'm not mistaken, they are already using gulp behind the scenes:
https://github.com/Shopify/slate-tools/blob/master/package.json

**Comment by lukekhamilton** [comment]
Hey @infernalsirius, yes I have seen that. However webpack is a far superior tool IMHO.

**Comment by panoply** [comment]
I have modified slate to work with webpack and support es6 – It's super strange that this wasn't to be supported out of the box but most developers coming up in this game don't know shit, so you gotta support these virgins who think that super average looking chick from Harry Potter is hot. Much like jQuery. 

Anyway, to get webpack working with slate. I use `yarn` and just add a `js` tasks within the scripts of your package.json, eg: 

```
  "scripts": {
    "js": "webpack -p --watch"
  }
```

Modify alias extensions in `webpack.config.js` to `.jsx` and then add scripts to your custom directories with that extension. From here just just run both tasks. As long as your output is a valid `.js` file, slates gulp task will push it. 

Alternatively you could also just drop slate all together, use `quickshot.js` to upload your themes and compile your own gulp task. All of which is pretty easy.

**Comment by NathanPJF** [comment]
@panoply I've edited your above comment to remove language that isn't permitted under this project's [code of conduct](https://github.com/Shopify/slate/blob/master/CODE_OF_CONDUCT.md).  If you have any questions, please send an email to this team's account slate@shopify.com.

**Comment by NathanPJF** [comment]
> I was wondering if webpack could be looked at for better managing this process locally

Thanks for sharing your thoughts on this @lukekhamilton.  In an early build of Slate, webpack was briefly discussed, but the team decided to stick with Gulp for running tasks under the hood in slate-tools.  However, having more control over the build system is something we’re aware folks are looking for.

> This could also them help get around the issues that currently exist with the shopify servers not supporting the later versions of SCSS too.

The central issue with SCSS is Liquid syntax.  Shopify’s compiler runs the job of converting Liquid to strings before compiling to CSS.  So variables like `{{ settings.primary_color }}` pulled from the theme editor, or Liquid filters pointing at Shopify hosted assets `background-image: {{ ‘bg-image.jpg | file_url }}` can exist in your `*.scss` files.  It was a decision on the team that the build system would work for themes being developed for the theme editor as a starting point and then iterate from there.  

If you feel webpack, or a plugin, can address the Liquid concern, I’m interested in hearing more.

>  I have modified slate to work with webpack and support es6

@panoply  Nice :thumbsup: 

Other devs have forked the build tools to suit their needs in the past.  The Shopify Theme Partner, Stylehatch, has their own forked version of Slate tools which you can checkout here: [GitHub - stylehatch/slate-tools: Tooling for Shopify themes using Slate.](https://github.com/stylehatch/slate-tools/).  You can see more on that conversation here: [Minify JavaScript assets · Issue #64 · Shopify/slate-tools · GitHub](https://github.com/Shopify/slate-tools/issues/64)

> Alternatively you could also just drop slate all together, use quickshot.js to upload your themes and compile your own gulp task.

Yep - if the current iteration of [Slate’s build tools](https://github.com/Shopify/slate-tools) is not working for you, we want to know; but people should know there are other options available right now.   You can use the template files and helper scripts of this repo without using the `@shopify/slate-tools` dependency.

For example, if you have a preferred task runner or build process, you may want to use that in conjunction with [Theme Kit](https://github.com/Shopify/themekit).  Theme Kit will manage deploys, and you can take care of the rest with our preferred tooling.  And there are other options such as Quickshot which has been mentioned before - I've heard people have had success with it.

**Comment by panoply** [comment]
@NathanPJF So my Harry Potter reference was too explicit for Shopify but Breitbart is totally cool? – ok, ok. I'll stop, but you've gotta admit it made you chuckle.

Slate imo meets the needs for 90% of use cases. Moving away from Timber and shipping with an entire workflow will 100% result in better theme development.

Some additional information regarding [quickshot](https://github.com/internalfx/quickshot) – This is a super handy tool for those who need to handle multiple store uploads. For example, one of the brands I work with has 3 seperate stores. The reason being, they require multiple currency at checkout level, which if anyone is not aware, Shopify does not support (yet), only multiple currency outside of checkout is possible when using Shopify.  Anyway, when theme modifications are required by this brand, quickshot works very effectively for their use case, because it will upload to all three stores and themes asynchronously, which makes keeping all 3 shops in sync very easily. Quickshot also supports es6 and sass out of the box (transpiling using babel).

**Comment by ChrisTowles** [comment]
@NathanPJF This is still a work in process and but due to a custom product builder I needed to use quite a bit of javascript and thus wanted to have webpack for the project. We forked the slate tools [here](https://github.com/roadid/slate-tools) but the overview is that in our shopify theme project we added a webpack.config.js that is processed by a gulp task. Works greats for both `slate watch` and 'slate start'.  Let me know if the community would like a more detailed example of this.

**Comment by t-kelly** [comment]
Going to close this issue as it is too general for an action item and is better reflected by other issues, such as:
- [Use `import` instead of JS globals](https://github.com/Shopify/slate/issues/250)
- [Manage .scss, .css, .scss.liquid, and .css.liquid files independently](https://github.com/Shopify/slate/issues/258)
- [Bundle splitting and dynamic imports](https://github.com/Shopify/slate/issues/266)
-
