### ISSUE TITLE
Developing with Slate results in a 503 timeout error on website

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate#191]
I can't be certain that it's Slate's pushing that's causing it but the past few days whilst developing with Slate, I've occasionally been given a 503 error page with the following error message:

> This page is temporarily unavailable because a device from your location is sending large amounts of web requests. Visitors from other locations can still view the page.

Screenshots attached.
![slatetimeout](https://user-images.githubusercontent.com/18140157/27996065-b4e0ef2e-64d1-11e7-9ab1-2a1983df26d4.png)

**Comment by t-kelly** [comment]
@ConduciveMammal is this occurring when you push to Github and then your Github tool pushes the latest version to your test store? I suspect that tool might be pushing files faster than our servers allow.

Otherwise, are you still experiencing this bug? Could you please provide more details on how to replicate it?

**Comment by ConduciveMammal** [comment]
Nah, this was just using default Slate to push directly to the store without GH.

Oddly enough, I've not actually seen this happen for a while, so perhaps there was just a glitch with Shopify’s servers?

**Comment by t-kelly** [comment]
Cool. Let us know if you see it again and we'll take another look!

**Comment by ben-lucidfusion** [comment]
I've gotten this error several times tonight while using slate v1.0.

**Comment by RustyDev** [comment]
I'm getting this error after updating to the latest package versions.
