### ISSUE TITLE
Theme name issue

### ISSUE THREAD

**Issue by lixonic** [Shopify/slate#192]
### Problem

Theme name is not getting updated

### Scope

I deployed the skeleton theme with `slate deploy` on my dev store. The theme name should be Slate,  right?

 
![blogger-theme edit debut shopify 2017-07-10 21-59-15](https://user-images.githubusercontent.com/934220/28029064-5176f7da-65bc-11e7-9613-e38b7aa97783.png)

**Comment by t-kelly** [comment]
Hey @lixonic. In order to rename an existing theme, you need to used the `rename` option under `actions`
![Alt text](https://monosnap.com/file/amUQYHKNkAxvtp1YdXwxP4az0qA0N9.png)

I'm assuming the situation you are describing is the result of replacing your `'live'` theme files (in this case Debut) with those of Slate's.

I believe the value in `theme_name` is only applied when you first install the theme, either from the theme store or from a `.zip`.
