### ISSUE TITLE
Issue with 'slate theme [theme-name]' command

### ISSUE THREAD

**Issue by saudslm** [Shopify/slate#248]
### Problem
`Error: ENOENT: no such file or directory, rename '/theme-dev/config-sample.yml' -> '/theme-dev/config.yml'`
There were some other bunch of of warnings:

<img width="569" alt="screen shot 2017-08-25 at 9 43 51 am" src="https://user-images.githubusercontent.com/12092793/29700036-f8b66eea-897a-11e7-9817-45631a08661e.png">

### Replication steps
I just followed the documentation [here](https://shopify.github.io/slate/) and executed this command to create a new instance of the theme: 

`slate theme [theme-name]`

### More Information

> Node v6.11.2

Any sort of help is appreciated.

**Comment by bmcminn** [comment]
Ran into this same issue on `Node v7.7.1` on Win7 Pro x64

Also super curious why this system "installs" node_modules" and then has to "unpack" them? Why doesn't it just run the native `npm install` routine on the generated theme folder?

**Comment by hisyam** [comment]
Just tried it right now and I have the same problem using `Node 8.4.0` and `npm 5.3.0`.

**Comment by t-kelly** [comment]
@saudslm @bmcminn @hisyam This looks like the issue I had when I released [`v0.12.0`](https://github.com/Shopify/slate/releases/tag/v0.12.0). The [`slate-src.zip`](https://sdks.shopifycdn.com/slate/0.12.0/slate-src.zip) in that version mistakenly changed the file structure, compared to [`v0.11.0 slate-src.zip`](https://sdks.shopifycdn.com/slate/0.11.0/slate-src.zip) -- that's why I was seeing the above error.

However, I immediately released a patch `v0.12.1` that should have fixed this problem. As you can see, [`slate-src.zip`](https://sdks.shopifycdn.com/slate/0.12.1/slate-src.zip) is now the same as it was in `v0.11.0`.

`slate` command line always requests the latest version of `slate-src.zip` so I wonder why you are getting the `v0.12.0` version...

Mind trying it again?

**Comment by t-kelly** [comment]
Just doubled checked `'https://sdks.shopifycdn.com/slate/latest/slate-src.zip'`, looks like it is still pointing to `v0.12.0`. Will get this fixed right now.

**Comment by saudslm** [comment]
@t-kelly just tried, still getting the same error

**Comment by t-kelly** [comment]
Okay it should be fixed now!

**Comment by t-kelly** [comment]
Thanks for bringing this to our attention @saudslm 🎉  😎

**Comment by saudslm** [comment]
no problem! Just checked it works now. Thanks @t-kelly for the quick fix.
