### ISSUE TITLE
Add option for style linting

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#261]
Style linters helps you avoid errors and enforce consistent conventions in your stylesheets. We have used them internally in themes development for a number of years.

We previously [removed style linting](https://github.com/Shopify/slate-tools/pull/9) in an effort to decrease Slate install times. I believe we can keep install times reasonable without sacrificing features.

Because style linting is an opinionated tool, it may not be needed by all developers. For this reason we should make it optional via the [Slate config file](https://github.com/Shopify/slate/issues/256)

Not sure which style linter we prefer. [Stylelint](https://github.com/stylelint/stylelint), [scsslint](https://github.com/brigade/scss-lint)?

**Comment by ConduciveMammal** [comment]
This is a definite necessary feature. 

As it stands, if something went wrong in any of dozens of SCSS files, Shopify rather uselessly states "Failed to compile SCSS", which is completely non-informative.

**Comment by t-kelly** [comment]
Interesting idea. Add linting to the `precommit` npm script hook so that linting will always occur when committing files.

**Comment by salasmx** [comment]
How we could integrate stylelint to our projects right now?

**Comment by t-kelly** [comment]
@salasmx you could install a stylelint plugin for you code editor (I can see that VSCode has one), and include a [.stylelintrc](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md) file in your project.

**Comment by salasmx** [comment]
Oh sorry, my mistake. I was wrong, I have stylelint installed. What I was thinking is about this: https://github.com/postcss/postcss#gulp because vscode or atom or whatever does not tell you that maybe one (or many) variables/mixings you are using are not declared already.

It just happened to me a minute ago when (because I'm working with two projects at same time, crazy thing) I wrote by mistake many variables from another project 😒 

Well I'm just saying, I think this is a serious feature request because sometimes .stylelintrc files are not enough.

**Comment by mattsince87** [comment]
Why can't you just give developers control over what packages we use for sass compilation, linting etc and just provide us with a local server and deployment method?

**Comment by t-kelly** [comment]
This has been started and shipped in the [1.x branch](https://github.com/Shopify/slate/tree/1.x).

Still working on a `lint` command to run linting. [More details here](https://github.com/Shopify/slate/projects/1#card-6750115).
