### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by Bek81** [Shopify/slate#271]
Hi,
I saw that there is a subfolder "customers" in the template folder. How can it be accessed?
I would handle the snippets folder with subfolders. Is it possible? how can I access the sub folders?

Tnx a lot.

**Comment by ConduciveMammal** [comment]
I don't believe subfolders are possible, with the exception of Customers. Also styles and scripts can also have subfolders if the global `theme.scss` & various script files reference them as Slate compiles them into the one Assets folder.

**Comment by NathanPJF** [comment]
That's correct @ConduciveMammal 
Customers is a folder already supported by Shopify.  It's not immediately apparent when you look at the online editor because the file name appears to be "customers/login" - but it's referring to a separate folder "customers".

Our build system does not support any subfolders for snippets or adding additional subfolders.  There's currently no plan to add this to Slate.

**Comment by GGalizzi** [comment]
This is probably my biggest gripe with developing for shopify, I'm an organization freak, and not having the ability to organize stuff into subfolders feels extremely dirty to me.

**Comment by t-kelly** [comment]
@GGalizzi totally hear you on that one. That's why the folder structure in Slate's `src` folder is different than that of `dist`. We could explore a similar transformation with snippets, which looks at all files AND folders inside the `src/snippets` directory and moves them to `dist/snippets`...

I'll create an issue for Slate v1 to explore this concept and how it may be applied to other directories like `sections/`
