### ISSUE TITLE
Unable to set logo_max_width in settings_data.json to greater than 450

### ISSUE THREAD

**Issue by taylorbryant** [Shopify/slate#278]
### Problem

Setting `logo_max_width` in `settings_data.json` to a number greater than 450 throws the following error: `Error: Setting 'logo_max_width' can't be greater than 450`.

### Replication steps

* Upload Slate theme to development Shopify store
* Go to Themes > [theme_name] > Actions > Edit Code
* Change `logo_max_width` in `settings_data.json` to a value greater than 450

### More Information

I understand that I may be missing something. I would just like some clarification, as I'm trying to upload a 1000px logo that covers the header area. Thanks for your help!

**Comment by NathanPJF** [comment]
@taylorbryant The 450 ceiling is set in the `{% schema %}` part of `header.liquid` which you can find in the `sections/` directory.  You can change the values there to what ever you'd like.  

However, that schema is just an example.  If you don't want to have a range picker for max logo width, then by all means remove that input and update the section file to suit your needs 😄 

Bit more info: The reason you cannot change the value from `settings_data.json` is because that JSON object is dependent on the schema defined in your section settings as well as general settings (`settings_schema.json`).  Shopify attempts to prevent any updates to `settings_data.json` that aren't supported by the theme or section settings.
