### ISSUE TITLE
Update/create a build task to: compile sass into css, add map and minify the resulting css file.

### ISSUE THREAD

**Issue by pdion** [Shopify/slate#290]
### Problem

Hello, I would like to update/create a build gulp task to compile sass into css, add map and minify the resulting css file. My problem is about npm/github.

How can I make a npm install of my forked slate-tools modules into my theme directory?

ie, in the theme directory run _npm install my-username/slate-tools_.

Thank you. 

### Replication steps

n/a

### More Information

n/a

**Comment by t-kelly** [comment]
You need to reference a local clone of your forked Github since your fork isnt published on NPM. It would look something like this:
```
"dependencies": {
    "bar": "file:../slate-forked/packages/slate-tools"
  }
```
[This Stackoverflow thread has more details](https://stackoverflow.com/questions/14381898/local-dependency-in-package-json). 

[Typically you could reference the forked Github directly](https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly), but [since we're using a monorepo structure for Slate this doesn't work](https://github.com/npm/npm/issues/2974). Hopefully NPM or Yarn will find a solution for this soon!
