### ISSUE TITLE
Issues with building my assets into dist folder. 

### ISSUE THREAD

**Issue by brandonpowell** [Shopify/slate#307]
I'm having a problem with the ``slate build``. All SCSS assets that add into global and they aren't building them into dist folder. I'm trying to add slick.scss and theme-slick.scss into dist folder.

**Comment by NathanPJF** [comment]
Hi, @brandonpowell 

We will need more information in order to help you with this one.  Please follow the new issue template that was generated to provide the following:

```
### Problem

*Succinct outline of the problem or request.*

### Replication steps

*How to replicate the problem. Screenshots or video?*

### More Information

*Any additional information which might be helpful.*
```

In particular, please provide replication steps for your setup and additional information such as:
* What does your `theme.scss` file look like?
* The version of SCSS `slick.scss` is compatible with.  Note that the online compiler only supports Sass v3.2 : https://shopify.github.io/slate/theme-scaffold/#sass-helpers
* Are you getting any errors in the command line?
* Are there any error messages when you go to your online editor at `/admin/themes/{theme-id}?key=assets/theme.scss.liquid`?

**Comment by brandonpowell** [comment]
I cannot see the dist folder anymore when every I build or deploy it. [VIdeo Link](https://www.youtube.com/watch?v=bZ0lSz1xhKU&feature=youtu.be)

**Comment by NathanPJF** [comment]
I watched the video, thanks for providing that.

I noticed that your editor is not showing your `node_modules/` folder or your `config.yml`.  Perhaps your editor is hiding any files/folders from view that are listed in the `.gitignore`.

**Comment by brandonpowell** [comment]
I have to remove the node_modules from ``.gitignore`` but nothing happen still gone. if want to add node_modules do I have to do like npm install -g @shopify/slate

**Comment by brandonpowell** [comment]
@NathanPJF Do I have to restart a new theme again.

**Comment by NathanPJF** [comment]
> I have to remove the node_modules from .gitignore but nothing happen still gone.

Did you ever setup your `config.yml` file?  That's missing from your setup in the video and your `deploy` shouldn't be working if you don't have one.  I feel like the reason you aren't seeing these files is because your editor is not showing anything in your `.gitignore` - which should be something you can configure your editor to stop doing.

> Do I have to restart a new theme again.

If you want your `node_modules` back, yep! 😄 
If you're unfamiliar with NPM and  node modules, I suggest checking out the Getting Started docs at npmjs - https://docs.npmjs.com/getting-started/what-is-npm

**Comment by brandonpowell** [comment]
@NathanPJF I restart my and got the ``node_module`` but still the slick.scss and slick-theme.scss not working here video --> [Video Here](https://www.youtube.com/watch?v=5MeQzb-t2to&feature=youtu.be) When every do ``slate build`` doesn't add them in dist fold might be doing something wrong.

**Comment by brandonpowell** [comment]
@NathanPJF I restart my and got the node_module but still the slick.scss and slick-theme.scss not working here video --> Video Here When every do slate build doesn't add them in dist fold might be doing something wrong.
