### ISSUE TITLE
Stylesheet of slick.scss and theme.slick.scss not working at all.

### ISSUE THREAD

**Issue by brandonpowell** [Shopify/slate#310]
I restart my and got the node_module but still, the slick.scss and slick-theme.scss not working here video --> [Video Here](https://www.youtube.com/watch?v=5MeQzb-t2to) When every do slate build doesn't add them in dist fold might be doing something wrong.

I check both theme.scss and theme.liquid everything types correctly.

**Comment by NathanPJF** [comment]
@brandonpowell, as requested here https://github.com/Shopify/slate/issues/307#issuecomment-333715003, please use the Issue template when submitting an issue. It will help us out when looking at your issue.  

If you are not sure what I mean by "issue template", it's the text that is autogenerated whenever you you make an issue.  It looks like this: https://github.com/Shopify/slate/blob/master/.github/ISSUE_TEMPLATE.md

---

In the video, you are importing `slick.scss` and `slick-theme.scss` into your `theme.scss` file using `@import`.

However, in your `theme.liquid` file you are generating a `<style>` tag asking for the the URL for both those Slick files.  This will not work because those were imported in `theme.scss` - the URL does not exist for `slick.scss` on its own.

If you want those files loaded as stand alone stylesheets on your website, you'll need to move them to the same level as `theme.scss`

```
styles/
  -- global/
  -- vendor/
  -- theme.scss
  -- slick.scss
  -- slick-theme.scss
```

![](http://take.ms/YyzaV)

**Comment by brandonpowell** [comment]
@NathanPJF Thank you, Sorry for type issue like I will fix up

**Comment by NathanPJF** [comment]
Assuming you now have this working @brandonpowell, so I'll close the issue. 😃
