### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by microsarah** [Shopify/slate#314]
### Problem
Slate is installed and was deploying successfully. I pushed changes to my repo and now I can't use any slate commands. Tried re-installing.

### Replication steps
<img width="570" alt="screen shot 2017-10-08 at 10 24 24 pm" src="https://user-images.githubusercontent.com/451523/31323579-b0220f98-ac77-11e7-9d25-f7929b5dff15.png">

### More Information
I had to remove and re-install node for the slate installation to work in the first place.

**Comment by t-kelly** [comment]
Not sure how much we can help you with this since this has to do with the way you have your machine configured. Best look inside your `Users/skh/.npm-global/lib` folder for a `bin/` directory and see if a `slate` bash file is there. Make sure that `bin/` directory is added to your PATH environment variable in your `~.bashrc` or `.zshrc` file.

Or uninstall your current version of node and install Node using [NVM](https://github.com/creationix/nvm). Great tool for managing Node versions. Maybe it will get things setup properly for you.

**Comment by microsarah** [comment]
Thanks for your response @t-kelly. I tried using NVM and did a complete re-install of Node. The `slate` bash file is in the `bin/` directory and the directory is added to my PATH environment. Let me know if you have any other insights.
