### ISSUE TITLE
Feature request: password parameter on the build task

### ISSUE THREAD

**Issue by laurent-le-graverend** [Shopify/slate#340]
### Problem

It's hard to run builds in a CI safely due to the lack of the password option in the build.

### More Information

ThemeKit has the `--password` flag, which is useful to avoid committing the theme password in the config file.
However, it's not possible to forward this parameter with Slate build.

It would be nice to be able to run:

```bash
slate build --env something --password $SOME_VAR
```

**Comment by t-kelly** [comment]
I believe the `slate deploy` and `slate watch` command would be more suited to receive these flags, since the `slate build` command does no interaction with Shopify servers.

A workaround for your CI woes would be to first run `slate build`, then `cd dist/`, then Themekit's `theme upload`

**Comment by t-kelly** [comment]
Good news @laurent-le-graverend, API config's are now available as environment variables in [Slate v1.x](https://github.com/Shopify/slate/tree/1.x)

You can set these env vars in a `.env` file, or declare them in your `.bashrc`/`.zshrc` file, or [declare them in your terminal instance](https://www.schrodinger.com/kb/1842).

Check out the [`slate-env`](https://github.com/Shopify/slate/tree/1.x/packages/slate-env) package for more details.

I'm going to leave this open still because I think having command line flags would also be nice.

**Comment by laurent-le-graverend** [comment]
Oh! That's really cool! Thanks for the update. The v1 seems promising!

**Comment by t-kelly** [comment]
I'm going to close this since the above is possible with by setting environment variables before running the desired command, e.g.:
```
SLATE_PASSWORD=123456 yarn deploy
```

Let me know if there are any objections, or added values by adding a flag based interface.
