### ISSUE TITLE
'itemCondition' schema.org meta tag

### ISSUE THREAD

**Issue by iamkeir** [Shopify/slate#348]
### Problem

Schema.org's `itemCondition` is an important (possibly mandatory) meta tag for products, proposing this be added to Slate. 

:tophat: @robcurry

### More Information

Pull request: https://github.com/Shopify/slate/pull/347

**Comment by iamkeir** [comment]
May need to go in 'Offers' section?

**Comment by NathanPJF** [comment]
>Schema.org's itemCondition is an important (possibly mandatory)

@iamkeir is there somewhere you read that stated this property is now mandatory?  I've run a couple URLs through Google structured data testing tool and didn't receive errors or warnings when `itemCondition` wasn't present.  https://search.google.com/structured-data/testing-tool/

I feel it would be a good addition, but couldn't add it to Slate at this point because there is nothing in Shopify's admin that allows merchants to control it's value.
