### ISSUE TITLE
Using Ampersand does nothing in theme.scss

### ISSUE THREAD

**Issue by rlambertsen** [Shopify/slate#360]
### Problem

When trying to nest pseudo classes on elements I really like to use the Ampersand (&). This is a basic function of SASS to call the parent class. Nesting is another great feature that without the Ampersand  is really just not fun at all. 

### Replication steps

```
.button {
  &:visited { }
  &:hover { }
  &:active { }
}
```

Try getting any of the pseudo classes to work after compiling

### More Information
Making sure that all SASS functionality is in working order would really help out a lot. I would be more than happy to jump on board to help fix issues like this. I am using this theme in a very large scale enterprise site

**Comment by jonathanmoore** [comment]
This sounds like a more general Shopify development question since Slate currently does not handle any SCSS processing.  Shopify processes all your SCSS for you that the Slate tool uploads.

Although I can confirm that ampersands do work with Shopify's SCSS processing with nested, combined and parent selectors.  We use it heavily in all our themes, and it works beautifully—as expected.  My guess is that you might be trying to apply the pseudo-classes to an HTML element where `visited`, `hover` or `active` are not valid.  For example those would not work with <button> or <input /> elements.

**Comment by t-kelly** [comment]
Ditto to @jonathanmoore's answer. `&` work, we also use them in all our themes.
