### ISSUE TITLE
Use of coffeescript for javascript files

### ISSUE THREAD

**Issue by octave** [Shopify/slate#364]
Would it be possible to use CoffeScript for some of the JavaScript assets?

**Comment by t-kelly** [comment]
Going to add this to the list of potential features in Slate v1.0. Thanks @octave.

**Comment by octave** [comment]
@t-kelly Sounds great! For now I created a `coffeescript` folder at the root of the slate project folder with my .coffee files. Then I'm using the coffeescript npm package to watch this folder and output the compiled files to src/scripts. It's still pretty fast.

**Comment by margolisj** [comment]
I'd personally lean towards using ES6 or Typescript over Coffeescript. Usage of Coffeescript has been steadily declining over the past two years.

**Comment by quinn** [comment]
@t-kelly @octave using modern javascript (ES6) rather than coffeescript will allow for a much broader audience of users and contributors. I would strongly discourage the use of coffeescript if the goal is to maximize development experience unless the goal is to make this a personal project (and the maintainer prefers coffeescript). 

for reference on why coffeescript is no longer a relevant technology:
https://robots.thoughtbot.com/replace-coffeescript-with-es6
https://www.toptal.com/javascript/whats-new-in-es6-perspective-coffeescript

this last one is from someone who still prefers coffeescript but now uses es6:
https://gist.github.com/benjie/d0e39fbe8a61bc30ed93#gistcomment-1814942

**Comment by octave** [comment]
@quinn @t-kelly sure that would make sense to go with ES6! Thanks for the suggestion.
