### ISSUE TITLE
Slate Start deleting Shopify Apps templates

### ISSUE THREAD

**Issue by bluedge** [Shopify/slate#401]
Yesterday, after installing some App from the Apps store I started Slate cli (slate start) 
and I noticed slate has deleted the templates the Shopify Apps added previously.

Is that expected, a bug?

Is there a way to avoid this pitfall other than including the Apps extra templates to my local environment?

**Comment by t-kelly** [comment]
Hey @bluedge, I [created an issue about this](https://github.com/Shopify/slate/issues/403) since it's been hovering around in the theme development community for a while but has not been properly addressed. 

Ultimately, yes it's a known issue since Slate currently has no way of detecting if a file has changed before override.

The best solution for now is to copy any app generated code into your project, so that when your working on your Slate theme it remains.
