### ISSUE TITLE
Documentation on how to use Slate w/ other Frameworks.

### ISSUE THREAD

**Issue by yankeyhotel** [Shopify/slate#406]
### Problem

I am curious if there are any resources for merging Slate with other frameworks. I have a working setup with Foundation and Slate, but I was curious if there might be a better way of doing it. 

I basically have 2 directories. One with everything for Foundation (styles and scripts) that dump into a `dist` directory that uses ThemeKit to watch files and upload them to Shopify. I guess I am only using the files from here as a starting point for my theme. Is there a way to merge the two better?

**Comment by t-kelly** [comment]
Hey @yankeyhotel -- are you asking about Slate v0 or [Slate v1.x](https://github.com/Shopify/slate/tree/1.x)?

**Comment by yankeyhotel** [comment]
I am currently starting this project so I'd like it to be as future proof as possible. So, I'll go with Slate v1.x. Thanks

**Comment by t-kelly** [comment]
Okay -- you should be able to include the Foundation dependencies in your `package.json` and then import them inside your `theme.js` so they are included in your bundle?

All good?

**Comment by yankeyhotel** [comment]
Yeah, thanks. I'm going to have to play with it, but I'll reach out again if I have trouble. Thanks for the fast response.

**Comment by gavsiu** [comment]
Did you get it working for Slate v1? Because I've pulled my hair out trying to get semantic-ui-sass to work. I managed to get the scss files imported, but I couldn't import the js files. It kept complaining about jQuery and the fixes don't work.

I gave up and tried installing Foundation through yarn because I thought it would be easier, but I can't seem to even import the scss files. I pointed them to the right place because it stopped complaining about unresolved locations. I'm guessing it's because Shopify doesn't support nested imports, but every single file references `util/_util.scss`.

I've been looking for guides or looking at how other themes do it, but they are all for Slate v0.

**Comment by prkirby** [comment]
@t-kelly @gavsiu I am having the same issue with Foundation 6. I really want to do this the "right" way. At current, I have foundation-sites as an package.json dependency, and have
`@import '~foundation-sites/scss/foundation.scss';`
in my theme.scss file. I had to play with that for a while, but am getting no resolution issues, however, the scss for foundation is not compiling and just failing silently. If I import the compiled css: 
`@import '~foundation-sites/dist/css/foundation';`
It imports no problem, so its not a directory resolution issue obviously. Really pulling my hair out here as well, as I haven't had this sort of issue in any other environment. Would love to re-open this issue as I can't find anything documenting this. 

Thanks!

**Comment by prkirby** [comment]
@t-kelly 

I'm guessing it has to do with this line here in slate-tools.schema.js:

```
  // Sometimes packages in node_modules need to be transpiled by Babel. To
  // allow this, change this config option so that it includes the following pattern:
  //
  // /node_modules\/(?!(MY-MODULE|ANOTHER-ONE)\/).*/
  //
  // See https://github.com/webpack/webpack/issues/2031 for more details
  'webpack.babel.exclude': (config) => config.get('webpack.commonExcludes'),

  // Paths to exclude for all webpack loaders
  'webpack.commonExcludes': [/node_modules/, /assets\/static/]
```
Which is referenced in config/parts/sass.js:

```
const sassRule = {
  test: /\.s[ac]ss$/,
  exclude: config.get('webpack.commonExcludes'),
};
```

Going to keep tweaking to see if I can't write an allow for just .scss and .css files within node_modules

**Comment by huguestennier** [comment]
@prkirby Instead of replying to a 8 months issue, I suggest you open a new one to make sure it gets proper attention 😄

**Comment by prkirby** [comment]
@huguestennier good point haha. I just didn't want to spam something that has already been addressed. 

If anyone lands here with the foundation headache, the problem is not with Slate at all. I just overlooked the fact that Foundation does not auto-export any of its scss modules anymore. So you either have to use `@include foundation-everything` after you import the library with `~foundation-sites/scss/foundation.scss`, or import each module individually. Hope this helps someone who was banging their head against the wall with this.
