### ISSUE TITLE
Yarn start wont work slate v1.0

### ISSUE THREAD

**Issue by pveen2** [Shopify/slate#414]
### Problem

So I set up everything like the description and then when i do:
yarn start:
✔  Compiled successfully in 2.228s!
⚠  You are about to deploy to the published theme. Continue? Yes

After that i get redirected to the SHOP url and not a localhost.
On the shop URL the css file is not in the theme. 

Only when i do yarn deploy i see the theme with the css added.

The i do yarn start again  and go to store url and i see the theme without the CSS.

How to fix this, hope you guys can help!

**Comment by t-kelly** [comment]
@pveen2 Please see https://github.com/Shopify/slate/tree/1.x#how-to-create-a-trusted-local-ssl-certificate

**Comment by pveen2** [comment]
@t-kelly it works, thanks:)!

**Comment by schellenbergk** [comment]
I'm having the same issue and not sure what I'm missing.   After I run `yarn start` with or without `--env` flag I always get `You are about to deploy to the published theme. Continue?`, then it uploads and opens my store on `myshopify.com`.  When I visit `https://localhost:8080 it shows `Cannot GET /`

**Comment by t-kelly** [comment]
@schellenbergk You are seeing the correct page contents when visiting `https://localhost:8080` (actually should improve this page and make it more obvious everything is okay).

The page that opens automatically is your development theme. You can tell its your development theme since the `<script>` tag at the bottom of your page source is pointing to `https://localhost:8080/assets/script.js` (or something like that). 

`https://localhost:8080` simply serves asset files like JS and SCSS, it does not serve liquid files.
