### ISSUE TITLE
Images in assets folder disappearing after slate deploy

### ISSUE THREAD

**Issue by specik** [Shopify/slate#462]
### Problem

We use a custom-built Shopify App to add additional images to products via metafields. When these are uploaded, we use the Assets API to save them to the assets folder. What appears to be happening is that when a theme deploy is done, it overwrites the contents of the assets folder completely. This results in all the images being deleted that are not part of the code push/repo. 

Are we missing something here? Should our Shopify App not be saving assets to the assets folder?

**Comment by t-kelly** [comment]
Hey @specik -- what you're describing is normal behaviour for how Slate works for now, however we do understand the problems it can cause. The `deploy` command does a complete sync between your dev environment and the store you're deploying to. If there are files in your store which are not in your dev environment, they get deleted. 

This is similar problem that others have with code changes done by apps, and them getting erased when using slate deploy. 

The best solution we can suggest for now is to copy these images into your `src/assets` folder of your slate project, that way they get uploaded when you do a deploy.

I'm going to close this issue since we are already aware of it and have a solution proposed in https://github.com/Shopify/slate/issues/403.

**Comment by patrickbjohnson** [comment]
Just updated my repo to match the suggestion by @t-kelly and it still wiped my repo. 

What was done: 
Uploaded images via our metafields app. Pulled down the assets folder and committed to repo. 
First deploy ran smoothly. Uploaded all assets (number was around 600). 

Second deploy managed to wipe out the assets director and remove all files that were uploaded during the first deploy. 

Any ideas, @t-kelly ?

**Comment by t-kelly** [comment]
@patrickbjohnson If the images remain in your `src/assets` folder, then there is no reason why they shouldn't be uploaded. What you're describing sounds bizarre, especially since it worked the first time?

On second thought, this makes me think that on top of having a [`sync`](https://github.com/Shopify/slate/issues/403) command to help with file changes from the code editor and apps, we should have a flag on `deploy` which toggles whether it should wipe all files and upload, or just upload and replace existing files..

**Comment by patrickbjohnson** [comment]
@t-kelly So I may have been a but preemptive. I pulled down the repo and then deploy and the asset count was ~600. 

On the second deploy (an hour or so later) the asset count was ~400. I immediately assumed it removed all the previous assets (which were pulled down from metafi). 

Once I logged in and refreshed my cache all images were still there.
