### ISSUE TITLE
Contents from custom fields deleted from the production theme when perform yarn deploy (v1.x)

### ISSUE THREAD

**Issue by AntoineGrenier** [Shopify/slate#509]
### Problem

yarn deploy remove all the contents from my production theme where I integrated my real data.

Maintenance will be almost infeasible if I have to reintegrate all the contents on the production theme every time I push something new. 

### Replication steps

1. yarn deploy => production theme.
2. Customer begin to integrate some data.
3. yarn deploy => production theme.
4. Customer data is gone.

### More Information

I've tried an experiment to understand how Shopify work with it's custom content:

1. Put a section into a static page.
2. Add content in the section.
3. Remove the section from the static page, the content is gone.
4. Put back the same section into the same static page, the original content is back.

At that moment I was thinking that the data from the database is linked to the section file. So, I try something new:

1. Put a section into a static page.
2. Add content in the section.
3. Remove the section from the static page, the content is gone.
4. Delete the section file completely from the theme from the Shopify admin.
5. Create a new section with the same name, same code, from the Shopify admin.
6. Put back the same section into the same static page, the original content is back.

Do I miss something with the deploy options to not have a "from scratch" production theme when I deploy? if not, if there a workaround to keep my contents?

**Comment by NathanPJF** [comment]
@AntoineGrenier I think you're describing the expected behaviour of the `settings_data.json` file.  That's where the information is saved for each section.

Based on your description of taking a section out and putting it back, it sounds like you're only ever removing the HTML from the editor.  Assuming the identifier in the json object of `settings_data.json` stays the same, when you add the section back it's going to be able to reference those same values.

Regarding the `yarn` commands: If your information is being removed on `deploy`, then perhaps you're aways uploading your local `settings_data.json` file which has no information in it.  Example:

https://github.com/Shopify/slate/blob/41b3269ff7164e9193aeb758a10554527dbb318f/packages/slate-theme/config-sample.yml#L21

**Comment by AntoineGrenier** [comment]
Thank you! That answer my question.
