### ISSUE TITLE
How can I deploy the theme?

### ISSUE THREAD

**Issue by magpiedigital** [Shopify/slate#562]
The docs say use `slate-tools deploy` but I just get

`-bash: slate-tools: command not found`

**Comment by reilnuud** [comment]
For v1, I use `yarn deploy`. Not sure what the npx command is.

**Comment by chrisberthe** [comment]
@magpiedigital if you're running that command directly in your terminal, it makes sense that you're seeing that output since `slate-tools`, most likely, isn't installed globally on your machine.

Can you clarify if you generated your new theme with `yarn create slate-theme my-new-theme`?

If you did, you should see `slate-tools` in the list of dependencies. We already have a set of `scripts` contained inside of the `package.json` that will call the `slate-tools` module (since when you install your dependencies, it becomes available in your `/node_modules` folder). Try running `yarn deploy` (or `npm run deploy` if using NPM) and this should work.

If you're not using Starter Theme as your starting point, let us know and we'll walk you through a few more steps.

**Comment by magpiedigital** [comment]
`npm run deploy` worked, thank you
