### ISSUE TITLE
VALID_LIQUID_TEMPLATES should be configurable

### ISSUE THREAD

**Issue by aschmoe** [Shopify/slate#588]
### Problem

VALID_LIQUID_TEMPLATES in https://github.com/Shopify/slate/blob/master/packages/slate-tools/tools/webpack/entrypoints.js#L5 seems like it should be passed through slate.config to allow theme modification.

### Replication steps

place `templates/collection.catalog.liquid` and `assets/scripts/collection.catalog.js` in theme.  No template bundle will be created or added to script-tags.liquid

### More Information

I'm happy to create a PR if this doesn't go against some internal decision.

**Comment by t-kelly** [comment]
Thanks @aschmoe -- added this to the beta backlog!

**Comment by dictions** [comment]
Is there a work around for this currently?

**Comment by t-kelly** [comment]
Looking at this closer, I don't think we need this to be configurable. Shopify only allows a particular list of template, and these are them.

![image](https://user-images.githubusercontent.com/4837696/45460660-f6807f00-b6cc-11e8-8db6-f231b49b1e7d.png)

However, the current solution does not cover alternative template, with naming like `page.alternative.liquid`. This is being discussed here https://github.com/Shopify/slate/issues/707

**Comment by diegopelaez** [comment]
Hey @t-kelly I can see that this is marked as done but I can't find any information on how it was solved and how can we create new alternate templates.

Also I like to point out that in the style-tags snippet Slate is using {{ template.name }} to validate the type of template, why don't use just {{ template }} which in this case will show you the real alternate template. Example:

If you have:
templates/collection.liquid
templates/collections.alternate.liquid

instead of doing:

```{%- if template.name == 'collection' -%}```

Slate should do:

```{%- if template == 'collection'  -%}```

then you can do:
```{%- if template == 'collection.build'  -%}```

**Comment by t-kelly** [comment]
Hey @diegopelaez -- tracking the change you're talking about in #707. This issue was more about making the list configurable, which is not needed.
