### ISSUE TITLE
Slate-tools format is not excluding static assets directory

### ISSUE THREAD

**Issue by b0123498765** [Shopify/slate#596]
### Problem

`slate-tools format` is formatting app minified js libraries stored in `/src/assets/static`.

### Replication steps

Save a js minified bundle to `/src/assets/static` then run `slate-tools format`.

### More Information

Exclude `/src/assets/static` from format command

**Comment by chrisberthe** [comment]
Hi @b0123498765 thanks for reporting this! I've opened up a PR (https://github.com/Shopify/starter-theme/pull/83) to exclude the `src/assets/static` folder from being formatted when running `yarn format`.

I'll leave it up to @t-kelly to decide whether or not we should ignore this directory from `slate-tools` instead of at the theme level.
