### ISSUE TITLE
No command for downloading from shopify

### ISSUE THREAD

**Issue by w-lemon** [Shopify/slate#601]
### Problem

*It will be great if you add new command like THEMEKIT's download command*
something like this 
```
slate-tools download
```

**Comment by t-kelly** [comment]
Hey @w-lemon -- for now this is not in the scope of Slate v1 due to how there are now very clearly defined 'source' files and 'dist' files. If we had a download command, it would download 'dist' files from Shopify servers. We would then need to reverse compile those files to get 'source' files. 

We understand that the developer workflow around working on an already implemented theme needs some improvement. Here is one proposal that might help https://github.com/Shopify/slate/issues/403
