### ISSUE TITLE
@include material design components

### ISSUE THREAD

**Issue by hcmlopes** [Shopify/slate#607]
I'm sorry but I had to edit this issue multiple times as I was figuring things out.

I would like to include **material.oi web components** into my shopify store. In order for webpack to find the modules I have modified the files dev.js webpack config line:69 and prod.js line: 64 with the following changes: 
   
  {loader: 'sass-loader', options: {sourceMap: false, **includePaths: ["./node_modules/"**]}}

These changes should allow sass-loader to find all of the @material components and compile. This seems to work fine as I would get a `Compiled successfully in 0.893s!` message.

I have come to find out that even before the changes I made, none of the styles were getting applied by `yarn start` which has been reported as an issue here [608](https://github.com/Shopify/slate/issues/608)

Now when I run `yarn deploy` or `yarn build` without my newly added `@import "@material/button/mdc-button";` everything works fine and all of the styles get applied. When I try to add the material component I get this error:
![image](https://user-images.githubusercontent.com/20449158/40696758-226dda1c-6395-11e8-8878-14671201634c.png)

Hopefully someone can shed some light on this.
Thank you

**Comment by hcmlopes** [comment]
I think I was able to fix this by adding `includePaths: ["./node_modules/"]` option into the sass-loader webpack dev.js and prod.js config file. After adding the path it compiles properly however I can't  verify this 100% since I am experiencing the same issue as reported here [608](https://github.com/Shopify/slate/issues/608)

dev.js webpack config line:69 and prod.js line: 64 changes:
`{loader: 'sass-loader', options: {sourceMap: false, includePaths: ["./node_modules/"]}}`

**Comment by jonathanmoore** [comment]
Like Slate, Material.io is moving towards the usage of CSS custom properties (CSS vars).
https://material.io/develop/web/docs/theming/#step-4-changing-the-theme-with-css-custom-properties
https://github.com/material-components/material-components-web/blob/47807b953ddf5a172f1bc50044105c38fffd3d97/packages/mdc-ripple/_mixins.scss#L50

With the way that Slate's `slate-cssvar-loader` package works it search all the SCSS files for any usage of var() to swap it out with the liquid variable.
https://github.com/Shopify/slate/blob/master/packages/slate-cssvar-loader/index.js#L49

There's another issue open to allow for the use of non-Liquid CSS vars.  In theory once this bug is fixed the error you're seeing should go away.
https://github.com/Shopify/slate/issues/524

**Comment by t-kelly** [comment]
#524 had been fixed and deployed in Slate Beta.3. This should be fixed too!
