### ISSUE TITLE
Confusion in Documentation of Slate Tools and slate-start

### ISSUE THREAD

**Issue by jonathan5572** [Shopify/slate#689]
### Problem

*Build, Deploy, and Start have similar-sounding explanations of their purpose and may lead to confusion how to to use. Similarly, the start command uploads a blank theme*

#### build
Builds a production-ready version of the theme by **compiling the files into the dist folder**.

`slate-tools build`

#### deploy
**Compiles** the theme and **uploads the dist folder** to the Shopify store.

`slate-tools deploy`

#### start
**Compiles** your local theme files **into a dist directory**, uploads these files to your remote Shopify store and finally boots up a local Express server that will serve most of your assets (i.e. CSS and JavaScript) from https://localhost:8080.

`slate-tools start`

### Start command uploading wrong?

Running `yarn slate-tools start` starts an upload of a blank starter-theme to your store/preview

![89 files](https://i.imgur.com/rZVsbzw.png)
89 files

Which is strange because this is an already-changed starter theme, and when I run `yarn slate-tools build` then `yarn slate-tools deploy` 

![109 files](https://i.imgur.com/hfwFcAh.png)
109 files

And then I refresh the preview and the changes appear.

I'm just wondering if there is a way to explain the proper order of tools to run? I know that `start` is supposed to boot up a local server and serve liquid assets from Shopify's servers, but I do not see my theme file changes when I use start. Only build+deploy, which is ~70 seconds each time, and has been a little frustrating.

Thank you!

**Comment by t-kelly** [comment]
Hey @jonathan5572 -- the reason you are seeing a different file count is that `slate-tools start` is a completely different build process intended for development only. It boots up a local file server to serve assets from, and as a result does not require as many files to be uploaded to Shopify servers.

`slate-tools deploy` is the production build pipeline and is intended to be used outside of developing. It uploads all assets to Shopify servers since it does not make use of the local asset server.
