### ISSUE TITLE
Getting error "Theme cannot be previewed" when starting new project

### ISSUE THREAD

**Issue by amritsub** [Shopify/slate#718]
### Problem

Getting this error during Step 4 here: https://github.com/Shopify/slate/wiki/4.-Start-developing

`Theme cannot be previewed because it's missing one of these required files: layout/theme.liquid, templates/index.liquid, templates/collection.liquid, templates/product.liquid, templates/page.liquid, templates/cart.liquid, templates/blog.liquid, config/settings_schema.json`

console output:
`
13:44:28 [development]Asset Perform Update to templates/blog.liquid at host XXXXXX.myshopify.com
	Status: 404 Not Found
	Errors: This file is not part of your theme.
`

^have 390 errors like this when running `npm start` for different files

### Replication steps

follow steps here creating a new project: https://github.com/Shopify/slate/wiki/Getting-Started

### More Information

Mac OS X El Capitan 
node v8.11.4 
npm v5.6.0

**Comment by monika** [comment]
I was also experiencing this same issue and it turned out I was using the `theme_store_id` listed in my themes.xml file instead of the `id` for that specific theme:

![id](https://user-images.githubusercontent.com/316762/45126131-a5014e80-b126-11e8-9b0f-f909aeab5706.png)

If this turns out to also be your issue, I think it might be worth clarifying a bit more in [Step 3](https://github.com/Shopify/slate/wiki/3.-Connect-to-your-store#setting-slate_theme_id) of the setup process.

**Comment by amritsub** [comment]
yup, this was my issue, the docs need to be updated. thanks @monika!
