### ISSUE TITLE
How to use PJAX?

### ISSUE THREAD

**Issue by isaac-martin** [Shopify/slate#768]
### Problem
Have tried to implement a few PJAX solutions, but due to the bundling of Webpack not sure not is possible? 

Have tried to implement with [Swup](https://github.com/gmrchk/swup), and obviously functions work on initial page load, but the second I click on a link to navigate to a new page the JS functions aren't called again. 

I need to add an event listener that is part of the SWUP API to run those functions, but because of the chunk files not sure if that is possible? 

```
document.addEventListener('swup:contentReplaced',() => {
// Do stuff here
});
```
For example I would do this in the `templates/product.js` 

```
import {load} from '@shopify/theme-sections';
import '../sections/product';
import '../sections/ingredient';
import '../lib/RandomBG';


document.addEventListener('DOMContentLoaded', () => {
  load('*');
});

document.addEventListener('swup:contentReplaced', () => {
  load('*');
});

```

But I guess when navigating to a product page from say index, the browser doesn't load the `template.product.js` so it can't even run that `swup:contentReplaced`  

Any help would be appreciated. Know its not really a bug with Slate but maybe In the way I am approaching this?

**Comment by t-kelly** [comment]
> But I guess when navigating to a product page from say index, the browser doesn't load the template.product.js

Are you sure `template.product.js` is not running? Have you tested with both `yarn start` and `yarn deploy`?

**Comment by t-kelly** [comment]
Sounds like your internal links are loading the page with AJAX. What framework are you using?

**Comment by isaac-martin** [comment]
Yeah so pages and content load fine, JS after is the problem. Am using [Swup](https://github.com/gmrchk/swup)
Theres some other options on the API there that I may try.

**Comment by t-kelly** [comment]
Makes sense. Run `yarn build` and look at `dist/snippets/script-tags.liquid`. You'll see there are Liquid conditions there that include `template.product.js` if the template being rendered is `product`. Since you're loading another page, that condition is false and instead a prefetch `<link>` is inserted. 

You'll need to configure Swup to mimic the behaviour of that snippet, or grab the `<script>` tags from `/product/x` and insert them into the head on internal page navigation.

Either way, this is not a problem with Slate. Closing.

**Comment by isaac-martin** [comment]
Thanks tom
