### ISSUE TITLE
layout.theme.js failed to load

### ISSUE THREAD

**Issue by ngkay** [Shopify/slate#802]
### Problem

I'm getting `Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID` even after creating a trusted local SSL certificate.
Up to now I've followed all the steps to setup from the slate wiki to create a new theme and the trusted local SSL cert.

<img width="509" alt="screen shot 2018-10-07 at 5 08 11 pm" src="https://user-images.githubusercontent.com/14224109/46586984-ef425c00-ca53-11e8-826a-bbab54798f91.png">
<img width="512" alt="screen shot 2018-10-07 at 5 12 21 pm" src="https://user-images.githubusercontent.com/14224109/46586999-34668e00-ca54-11e8-953b-7db4c797d26c.png">

### Replication steps

 Run `yarn start` and Chrome opens up `localhost:3002` but styles aren't being loaded and injected.

**Comment by rainerbird** [comment]
I had a similar issue, upon reading the wiki looks like assets are served from IP address instead of localhost for this version - and they are looking into ways how to create an SSL cert:

https://github.com/Shopify/slate/wiki/How-to-create-a-trusted-local-SSL-certificate

> As of Slate v1.0.0-beta.7, we are now defaulting to referencing assets using your local IP address on port 3001 (xxx.xxx.xxx.xxx:3001). We're still working out the kinks, one of which is how to create a SSL cert. This guide is still applicable for beta.6 versions and below.

To continue for time being I navigated directly to the asset file and clicked under advance to proceed to the asset file and now my dev site will load.

**Comment by huguestennier** [comment]
Hey @ngkay! Thanks for the issue.

We're working on it, related issue here : https://github.com/Shopify/slate/issues/777

Going to close this for now but thanks for reporting
