### ISSUE TITLE
Fonts from shopify cdn do not load from localhost

### ISSUE THREAD

**Issue by marcnewport** [Shopify/slate#803]
### Problem

When in development mode (localhost) fonts from the shopify cdn do not load. The following error message is logged to the console:

```
GET https://fonts.shopifycdn.com/libre_baskerville/librebaskerville_n7.xxx.woff2?&hmac=xxx
net::ERR_ABORTED 406 (Invalid 'hmac' query string parameter)
```

### Replication steps

- In a theme liquid file, use the liquid filter `| font_face` to load a font
- Preview your theme on localhost using `yarn start`

**Comment by huguestennier** [comment]
We're working on a fix with the Core team. Will update this issue when we have a solution.

**Comment by huguestennier** [comment]
@marcnewport I opened a new issue with our findings regarding the problem here : https://github.com/Shopify/slate/issues/809.

Workaround for now would be to visit your `.myshopify.com` domain first as this will cache the fonts so you should be able to access them visiting `localhost:XXXX` after. Not a perfect solution, I oblige.

Gonna close this issue to keep https://github.com/Shopify/slate/issues/809 as the main one. Thanks for reporting this bug.
