### ISSUE TITLE
No build tools flow

### ISSUE THREAD

**Issue by NathanPJF** [Shopify/slate#82]
In the getting started section there’s a quote that says:

> Node 4+ is supported, but 6+ is recommended to fully benefit from Slate. If you want the template files without the build tools, get the latest zip here.

### Issue

 This download gives you the `src` files; not a distribution folder.  So you would still need the build tools installed to use it.

1. This is confusing - do I need the build tools or not?
2. Should the link be to an already compiled theme? i.e. The `dist` version?

### Suggestion

* Re-write this section as two separate thoughts.
* Clarify what the zip you're downloading is for (two options below)

---

## Getting started

> Node 4+ is supported, but 6+ is recommended to fully benefit from Slate.

The steps below walk through installing Slate globally and configuring your development theme to sync with your store.  You can `[download a zip here](link to src files)` of just the theme files, however you will require Slate's build tools to compile theme into a working theme.

-- or --

The steps below walk through installing Slate globally and configuring your development theme to sync with your store.  If you want the theme files without the build tools dependency, `[get the latest zip here](link to dist files)`.

**Comment by celsowhite** [comment]
I was also confused by this when reading the documentation. I opted to download the template files without the build tools because I have a custom gulp build process I use across dev platforms. 

I still wanted the Slate sync commands because I find them useful.

I'm in strong favor of the 2nd description you listed to make things clearer. I also think the link should be to an already compiled theme (dist folder.) It will make it easier to get started instead of having to manually remove and restructure files within the src.
