### ISSUE TITLE
function scope issue with import JS

### ISSUE THREAD

**Issue by philipstampe** [Shopify/slate#836]
Hi

I'm using some two external JS files located in assets/scripts
The first one is 'lazysizes.min.js' the other one is 'custom.js' file

In my theme.js file located in assets/scripts/layout

I have the following code in the top of theme.js

`import "../lazysizes.min.js";
import "../custom.js";`

Both files start with a console log, so I can see that the files is loaded. But when I in theme.js try to call a function that exists in custom.js i get the following error:

Uncaught ReferenceError: functionName is not defined

It works if i move the code from custom.js into theme.js, and the 'lazysizes.min.js' file gets loaded and works aswell.

It's my first time using this setup for Shopify, so i can easily have missed something.

Hopefully someone can clarify, if this is an error or that im doing something wrong

**Comment by huguestennier** [comment]
Are you exporting your function? I suggest you give a read on [modules import/export ](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export).

_custom.js_
```JS
export default function test() {
  console.log('test');
}
````
_theme.js_
```JS
import test from '../custom.js';

test();
```

Going to close this since it's not Slate related but the code above works and should give you a good idea.
