### ISSUE TITLE
featured-collection missing if condition

### ISSUE THREAD

**Issue by preston206** [Shopify/slate#895]
### Problem

In Slate 0.14.0, when creating a new theme **featured-collection.liquid** has a rogue `{% else %}`. The page does render though, which is why I think the issue hasn't been logged yet.

### Replication steps

1) `slate theme new-theme`
2) open *featured-collection.liquid*
3) see *line 39*
4) that `{% else %}` does not have a matching `{% if %}`

### More Information

My code proposal:
```
{% if section.settings.title != blank %}
  <h2>{{ section.settings.title | escape }}</h2>
{% endif %}

{%- assign collection = collections[section.settings.collection] -%}

{% if collection.products != blank %}

  {% for product in collection.products limit: 6 %}
    <a href="{{ product.url | within: collection }}">

      {% if product.featured_image != blank %}
        {{ product.featured_image.src | img_url: '480x480' | img_tag: product.title }}
      {% endif %}

      <p>{{ product.title }}</p>
    </a>

    <p>
      {% if product.compare_at_price > product.price %}

        {% if product.price_varies %}
          {%- assign sale_price = product.price | money -%}
          {{ 'products.product.on_sale_from_html' | t: price: sale_price }}
        {% else %}
          {{ 'products.product.on_sale' | t }}
          {{ product.price | money }}
        {% endif %}

      {% else %}

        {% if product.price_varies %}
          {%- assign price = product.price | money -%}
          {{ 'products.product.from_text_html' | t: price: price }}
        {% else %}
          {{ product.price | money }}
        {% endif %}

      {% endif %}
    </p>
  {% endfor %}

{% else %}

  {% for i in (1..6) %}
    <a href="#">
      {% capture current %}{% cycle 1, 2, 3, 4, 5, 6 %}{% endcapture %}
      {{ 'product-' | append: current | placeholder_svg_tag: 'placeholder-svg placeholder-svg--small' }}

      <p>
        {{ 'homepage.onboarding.product_title' | t }}
      </p>
    </a>

    <p>{{ 1999 | money }}</p>
  {% endfor %}

{% endif %}
```

NOTES:
- notice the additional `if` near the top to check for *products*
- moving the last `endfor` inside the new `if` block

**Comment by jonathanmoore** [comment]
For issues with the Starter Theme, I'd recommend adding it in that specific repo since it's separate from Slate.
https://github.com/Shopify/starter-theme

Although looking through the file again, all of the uses of `{% else %}` are correct and valid.  The line numbers you mention don't quite match up to the repo, but I'm assuming you're talking about line 50 https://github.com/Shopify/starter-theme/blob/master/src/sections/featured-collection.liquid#L50

That specific `[% else %}` is a valid condition for when the for loop returns false.
`{% for product in collection.products limit: 6 %}`

https://help.shopify.com/en/themes/liquid/tags/iteration-tags#else

**Comment by preston206** [comment]
ok thank you for clarifying. Sorry I posted in the wrong spot.
