### ISSUE TITLE
Refused to apply style from '...' on Slate beta.14

### ISSUE THREAD

**Issue by JulienHe** [Shopify/slate#970]
### Problem

<img width="639" alt="screen shot 2019-02-04 at 14 25 32" src="https://user-images.githubusercontent.com/718868/52191602-ebe7a180-2888-11e9-9688-8791d6cfa125.png">

This is what I have in my stylesheet.

![code](https://user-images.githubusercontent.com/718868/52191725-81833100-2889-11e9-8fd2-6fc7f27d130d.png)

This is the problem I encounter right now. I know I'm not the only one to have it.
**Slate version**: beta.14.
**Node version** : v10.7
**Yarn version**: 1.13.0

Does anyone have any suggestions ?

Also my regular scss is working well, I just need to have the .scss.liquid to have my images as background image. If you have any other solution, please help! 

### Additional information

I work on local `https://localhost:3000/?_fd=0` and my ssl is set.

**Comment by JulienHe** [comment]
Found the issue. Apparently I can't have &--, is it normal?

**Comment by jonathanmoore** [comment]
That's 100% normal. The .scss.liquid files get uploaded to Shopify's servers so that they can render both the liquid and SCSS.  Shopify's fork of SCSS is based on the older 3.2 version of Sass prior to the introduction of BEM style nesting.

If you want to take advantage of the latest, you'll need to use Slate's local SCSS processing free of all Liquid.
